// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1bD9fD5CdPCC2Iyr6rR-xBcrySD6tty0',
    appId: '1:703516290103:web:e10c0fc16811eed8e363b2',
    messagingSenderId: '703516290103',
    projectId: 'testprojmobile-4c9db',
    authDomain: 'testprojmobile-4c9db.firebaseapp.com',
    storageBucket: 'testprojmobile-4c9db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpnvJEQDeETgqElF1uMHTR_p8RHZ-mH9g',
    appId: '1:703516290103:android:35a3fb735688a8e1e363b2',
    messagingSenderId: '703516290103',
    projectId: 'testprojmobile-4c9db',
    storageBucket: 'testprojmobile-4c9db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDua12QFOn-w9JykmpMxdJJX6E5qSkuQao',
    appId: '1:703516290103:ios:04c8007e524df0d8e363b2',
    messagingSenderId: '703516290103',
    projectId: 'testprojmobile-4c9db',
    storageBucket: 'testprojmobile-4c9db.appspot.com',
    androidClientId: '703516290103-bjuqejb6luehbsddt2hpdjccdrftqj2d.apps.googleusercontent.com',
    iosClientId: '703516290103-glnmckak45nbn0646bvcigjorbk3tqbm.apps.googleusercontent.com',
    iosBundleId: 'com.example.testprojmobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDua12QFOn-w9JykmpMxdJJX6E5qSkuQao',
    appId: '1:703516290103:ios:04bbe30682734365e363b2',
    messagingSenderId: '703516290103',
    projectId: 'testprojmobile-4c9db',
    storageBucket: 'testprojmobile-4c9db.appspot.com',
    androidClientId: '703516290103-bjuqejb6luehbsddt2hpdjccdrftqj2d.apps.googleusercontent.com',
    iosClientId: '703516290103-6i3fp7s8a26qdenu73dri0brc8sv0b4v.apps.googleusercontent.com',
    iosBundleId: 'com.example.testprojmobile.RunnerTests',
  );
}
